from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path ('', views.index, name = "index"),
    path ('about/', views.about, name = "about"),
    path ('change_password/', views.change_password, name = "change_password"),
    path ('dashboard/', views.dashboard, name = "dashboard"),
    path ('deposit_wallet/', views.deposit_wallet, name = "deposit_wallet"),
    path ('deposit/', views.deposit, name = "deposit"),
    path ('interest_wallet/', views.interest_wallet, name = "interest_wallet"),
    path ('interest/', views.interest, name = "interest"),
    path ('invest/', views.invest, name = "invest"),
    path ('investment/', views.investment, name = "investment"),
    path ('log/', views.log, name = "log"),
    path ('manual/', views.manual, name = "manual"),
    path ('new/', views.new, name = "new"),
    path ('partners/', views.partners, name = "partners"),
    path ('plan/', views.plan, name = "plan"),
    path ('preview', views.preview, name = "preview"),
    path ('profile_setting/', views.profile_setting, name = "profile_setting"),
    path ('promotional_tool/', views.promotional_tool, name = "promotional_tool"),
    path ('register/', views.register, name = "register"),
    path ('login/', views.custom_login, name = "login"),
    path ('logout/', views.custom_logout, name = "logout"),
    path ('reset/', views.reset, name = "reset"),
    path ('subscribe/', views.subscribe, name = "subscribe"),
    path ('support/', views.support, name = "support"),
    path ('terms/', views.terms, name = "terms"),
    path ('ticket/', views.ticket, name = "ticket"),
    path ('transfer_balance/', views.transfer_balance, name = "transfer_balance"),
    path ('twofactor/', views.twofactor, name = "twofactor"),
    path ('users/', views.users, name = "users"),
    path ('withdraw/', views.withdraw, name = "withdraw"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('template_activate_account', views.template_activate_account, name='template_activate_account'),
    path('reset/<uidb64>/<token>', views.passwordResetConfirm, name='password_reset_confirm'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path ('bitcoin/', views.bitcoin, name = "bitcoin"),
    path ('banktransfer/', views.banktransfer, name = "banktransfer"),
    path ('history/', views.history, name = "history"),
    path ('pin/', views.pin, name = "pin"),
    path ('processing/', views.processing, name = "processing"),
    path ('terms_condition/', views.terms_condition, name = "terms_condition"),
    path ('privacy/', views.privacy, name = "privacy"),
]