# Generated by Django 5.0.7 on 2024-07-12 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('main_balance', models.CharField(default='10', max_length=200, null=True)),
                ('total_deposit_balance', models.CharField(default='0', max_length=200, null=True)),
                ('interest_balance', models.CharField(default='0', max_length=200, null=True)),
                ('total_withdraw', models.CharField(default='0', max_length=200, null=True)),
                ('total_invest', models.CharField(default='0', max_length=200, null=True)),
                ('time', models.DateField(auto_now=True)),
                ('trnsaction_id', models.CharField(default='0', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
