# Generated by Django 5.0.7 on 2024-07-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
