# Generated by Django 5.0.7 on 2024-07-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_bitcoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoin',
            name='transactionid',
            field=models.CharField(default='FDG637GDJYU**', max_length=200, null=True),
        ),
    ]
