# Generated by Django 5.0.7 on 2024-07-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_alter_bitcoin_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
