# Generated by Django 5.0.7 on 2024-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_remove_transfer_accountnumber_remove_transfer_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='purpose',
        ),
        migrations.AddField(
            model_name='transfer',
            name='rate',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
