# Generated by Django 5.0.7 on 2024-07-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_remove_transfer_purpose_transfer_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='wallet',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
