# Generated by Django 5.0.7 on 2024-07-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_customerdeposit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customerdeposit',
        ),
    ]
