# Generated by Django 5.0.7 on 2024-07-13 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_delete_customerdeposit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depositlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('amount', models.CharField(max_length=200, null=True)),
                ('time', models.DateField(auto_now=True)),
                ('transactionid', models.CharField(default='FDG637GDJYU**', max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending...', 'Pending...'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending...', max_length=200)),
                ('rate', models.CharField(default='4', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
