# Generated by Django 5.0.7 on 2024-07-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0018_alter_depositlistimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='trnsaction_id',
            field=models.CharField(default='GHGSH4748HDH', max_length=200, null=True),
        ),
    ]
